export { default as ProfilePage } from './ProfilePage.vue'
export { default as StoryPage } from './StoryPage.vue'
export { default as ExperiencePage } from './ExperiencePage.vue'
export { default as JobBoxPage } from './JobBoxPage.vue'
export { default as ProfileLayout } from './ProfileLayout.vue'
